import re
import sys
from pathlib import Path

# The original snk animation uses the first 74% of the loop.
# The remaining time is reserved for the custom AJR finale.
PHASE = 0.74

GRID_COLS = 53
GRID_ROWS = 7
GRID_PITCH = 16
GRID_W = GRID_COLS * GRID_PITCH
GRID_H = GRID_ROWS * GRID_PITCH

# Stop the snake while it is returning, fully inside the calendar.
# All four body segments are forced onto the same row so the body never splits.
STOP_X = 512
STOP_Y = 48

FONT = {
    "A": ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
    "J": ["11111", "00100", "00100", "00100", "00100", "10100", "01100"],
    "R": ["11110", "10001", "10001", "11110", "10100", "10010", "10001"],
}


def letter_targets():
    """Return pixel targets grouped by A, J and R."""
    pitch = 11
    size = 9
    gap = 2
    x0 = 250
    y0 = 12
    groups = []
    offset = 0

    for ch in "AJR":
        pts = []
        for row, line in enumerate(FONT[ch]):
            for col, bit in enumerate(line):
                if bit == "1":
                    pts.append((x0 + (offset + col) * pitch, y0 + row * pitch))
        groups.append(pts)
        offset += 5 + gap

    return groups, size


def active_cells(svg):
    """Collect every real contribution cell generated by snk."""
    cells = []
    pattern = re.compile(
        r'<rect class="c ([^"]+)" x="(\d+(?:\.\d+)?)" y="(\d+(?:\.\d+)?)" rx="2" ry="2"/>'
    )
    for match in pattern.finditer(svg):
        cells.append((float(match.group(2)), float(match.group(3))))
    return cells


def build_complete_grid():
    """Build a deterministic 53x7 gray calendar behind the real contribution cells."""
    parts = ['<g id="complete-grid" pointer-events="none">']
    for col in range(GRID_COLS):
        for row in range(GRID_ROWS):
            x = 2 + col * GRID_PITCH
            y = 2 + row * GRID_PITCH
            parts.append(
                f'<rect class="grid-slot" x="{x}" y="{y}" width="12" height="12" rx="2" ry="2"/>'
            )
    parts.append('</g>')
    return ''.join(parts)


def build_final_clear(cells):
    """Cover every real active cell with its empty gray state during the finale."""
    parts = ['<g id="final-consumption-check" pointer-events="none">']
    for x, y in cells:
        parts.append(
            f'<rect class="final-clear" x="{x:g}" y="{y:g}" width="12" height="12" rx="2" ry="2"/>'
        )
    parts.append('</g>')
    return ''.join(parts)


def stop_snake_keyframes(style):
    """Freeze the complete snake on one grid row while it is returning left."""
    stops = [STOP_X, STOP_X + 16, STOP_X + 32, STOP_X + 48]

    for idx, stop_x in enumerate(stops):
        pattern = re.compile(rf"@keyframes s{idx}\{{(.*?)\}}(?=\.s\.s{idx})")
        match = pattern.search(style)
        if not match:
            raise RuntimeError(f"Could not find snake segment s{idx}")

        body = match.group(1)
        frames = []
        for fm in re.finditer(
            r"([\d.,%]+)\{transform:translate\((-?\d+(?:\.\d+)?)px,(-?\d+(?:\.\d+)?)px\)\}",
            body,
        ):
            percentages = [float(p.replace('%', '')) for p in fm.group(1).split(',')]
            frames.append((percentages, float(fm.group(2)), float(fm.group(3)), fm.group(0)))

        crossing = None
        seen_right = False
        prev = None

        for percentages, x, y, raw in frames:
            p = max(percentages)
            if x >= 780:
                seen_right = True

            if seen_right and prev is not None:
                pp, px, _ = prev
                if px > stop_x >= x and x < px:
                    ratio = (px - stop_x) / (px - x)
                    cp = pp + (p - pp) * ratio
                    crossing = cp
                    break

            prev = (p, x, y)

        if crossing is None:
            raise RuntimeError(f"Could not find return crossing for snake segment s{idx}")

        new_parts = []
        for percentages, x, y, raw in frames:
            if max(percentages) < crossing:
                new_parts.append(raw)

        # Every segment ends on the exact same row, 16px apart.
        new_parts.append(
            f"{crossing:.2f}%{{transform:translate({stop_x}px,{STOP_Y}px)}}"
        )
        new_parts.append(
            f"100%{{transform:translate({stop_x}px,{STOP_Y}px)}}"
        )

        style = style[:match.start(1)] + ''.join(new_parts) + style[match.end(1):]

    return style


def build_css(ms, groups):
    css = [
        ".grid-slot{shape-rendering:geometricPrecision;fill:var(--ce);stroke-width:1px;stroke:var(--cb)}",
        f".final-clear{{shape-rendering:geometricPrecision;fill:var(--ce);stroke-width:1px;stroke:var(--cb);opacity:0;animation:final-clear {ms}ms linear infinite}}",
        "@keyframes final-clear{0%,74.85%{opacity:0}75%,99.75%{opacity:1}100%{opacity:0}}",
        f".ajr-dot{{opacity:0;fill:var(--cs);animation-duration:{ms}ms;animation-timing-function:cubic-bezier(.22,.75,.3,1);animation-iteration-count:infinite;transform-box:fill-box;transform-origin:center}}",
    ]

    # A is completed first, then J, then R.
    windows = [(75.5, 81.5), (82.3, 88.3), (89.1, 95.1)]
    mouth_x = STOP_X - 4
    mouth_y = STOP_Y + 2

    counter = 0
    for letter_index, pts in enumerate(groups):
        start_window, end_window = windows[letter_index]
        n = max(1, len(pts))
        usable = (end_window - start_window) * 0.72

        for local_i, (tx, ty) in enumerate(pts):
            # True one-by-one emission: each block has its own start time.
            start = start_window + (local_i / n) * usable
            puff = start + 0.38
            arrive = min(end_window, start + 1.35)
            hold = 97.2
            fade = 99.0

            # Small mouth puff instead of a large spray.
            puff_dx = -18 - (local_i % 2) * 3
            puff_dy = (-5, -2, 2, 5)[local_i % 4]
            dx = tx - mouth_x
            dy = ty - mouth_y

            css.append(
                f".ajr-{counter}{{animation-name:ajr-{counter}}}"
                f"@keyframes ajr-{counter}{{"
                f"0%,{start - 0.03:.2f}%{{opacity:0;transform:translate(0px,0px) scale(.45)}}"
                f"{start:.2f}%{{opacity:1;transform:translate(-2px,0px) scale(.62)}}"
                f"{puff:.2f}%{{opacity:1;transform:translate({puff_dx}px,{puff_dy}px) scale(.82)}}"
                f"{arrive:.2f}%,{hold:.2f}%{{opacity:1;transform:translate({dx}px,{dy}px) scale(1)}}"
                f"{fade:.2f}%,100%{{opacity:0;transform:translate({dx}px,{dy}px) scale(.85)}}"
                f"}}"
            )
            counter += 1

    return ''.join(css)


def build_overlay(groups, size):
    mouth_x = STOP_X - 4
    mouth_y = STOP_Y + 2
    parts = ['<g id="ajr-finale" pointer-events="none">']
    counter = 0

    for pts in groups:
        for _ in pts:
            parts.append(
                f'<rect class="ajr-dot ajr-{counter}" x="{mouth_x}" y="{mouth_y}" width="{size}" height="{size}" rx="2"/>'
            )
            counter += 1

    parts.append('</g>')
    return ''.join(parts)


def clip_snake(svg):
    """Make it impossible for the snake to render outside the 53x7 grid."""
    clip = (
        f'<defs><clipPath id="snake-grid-clip">'
        f'<rect x="0" y="0" width="{GRID_W}" height="{GRID_H}"/>'
        f'</clipPath></defs>'
    )
    svg = svg.replace('</desc>', '</desc>' + clip, 1)

    matches = list(re.finditer(r'<rect class="s s\d"[^>]*/>', svg))
    if len(matches) != 4:
        raise RuntimeError(f"Expected 4 snake segments, found {len(matches)}")

    start = matches[0].start()
    end = matches[-1].end()
    snake_markup = svg[start:end]
    return (
        svg[:start]
        + '<g id="snake-body" clip-path="url(#snake-grid-clip)">'
        + snake_markup
        + '</g>'
        + svg[end:]
    )


def validate(svg, active_count):
    """Fail the workflow instead of publishing a visually inconsistent SVG."""
    expected_slots = GRID_COLS * GRID_ROWS
    if svg.count('class="grid-slot"') != expected_slots:
        raise RuntimeError("Complete gray grid was not generated correctly")

    if svg.count('class="final-clear"') != active_count:
        raise RuntimeError("Not every real contribution cell has a finale clear state")

    if 'id="snake-grid-clip"' not in svg or 'id="snake-body"' not in svg:
        raise RuntimeError("Snake clipping was not applied")

    for idx in range(4):
        expected = f"translate({STOP_X + idx * 16}px,{STOP_Y}px)"
        if expected not in svg:
            raise RuntimeError(f"Snake segment s{idx} does not have a deterministic stop")


def patch(path):
    p = Path(path)
    svg = p.read_text()
    cells = active_cells(svg)

    match = re.search(r"animation:none\s+(\d+)ms", svg)
    if not match:
        raise RuntimeError(f"Could not find snk animation duration in {path}")

    old = int(match.group(1))
    new = round(old / PHASE)
    groups, size = letter_targets()

    style_start = svg.index('<style>') + len('<style>')
    style_end = svg.index('</style>')
    style = svg[style_start:style_end].replace(f'{old}ms', f'{new}ms')

    # Compress the original snk timing to leave room for the finale.
    def scale_percent(match):
        value = float(match.group(1))
        if value >= 99.999:
            return '100%'
        scaled = value * PHASE
        return f'{scaled:.2f}'.rstrip('0').rstrip('.') + '%'

    style = re.sub(r"(?<![\w.-])(\d+(?:\.\d+)?)%", scale_percent, style)
    style = stop_snake_keyframes(style)
    style += build_css(new, groups)

    svg = svg[:style_start] + style + svg[style_end:]

    # Put a complete gray calendar behind the real snk cells so the snake can
    # never appear to travel through a missing/invisible square.
    first_cell = svg.find('<rect class="c"')
    if first_cell == -1:
        raise RuntimeError("Could not find contribution grid markup")
    svg = svg[:first_cell] + build_complete_grid() + svg[first_cell:]

    # Place the deterministic 'everything has been eaten' layer above the
    # contribution cells but below the snake.
    first_snake = svg.find('<rect class="s s0"')
    if first_snake == -1:
        raise RuntimeError("Could not find snake markup")
    svg = svg[:first_snake] + build_final_clear(cells) + svg[first_snake:]

    svg = clip_snake(svg)
    svg = svg.replace('</svg>', build_overlay(groups, size) + '</svg>')

    validate(svg, len(cells))
    p.write_text(svg)


for filename in sys.argv[1:]:
    patch(filename)
